const toImageItems = (basePath, fileNames, prefix) =>
  fileNames.map((fileName, index) => ({
    title: `${prefix} ${String(index + 1).padStart(2, "0")}`,
    path: `${basePath}/${fileName}`,
    kind: "image"
  }));

const buildProject = (slug, title, basePath, fileNames) => ({
  slug,
  title,
  cover: fileNames[0] ? `${basePath}/${fileNames[0]}` : "",
  summary: title,
  items: toImageItems(basePath, fileNames, title)
});

const uiFiles = [
  "1.jpg",
  "2@1x.png",
  "3@1x.png",
  "4@1x.png",
  "5@1x.png",
  "6@1x.png",
  "7@1x.png",
  "8@1x.png",
  "9@1x.png",
  "10@1x.png",
  "11@1x.png",
  "12@1x.png",
  "13@2x.png",
  "14@1x.png",
  "15@1x.png",
  "16@1x.png",
  "17@1x.png",
  "18@1x.png",
  "19@1x.png",
  "20@1x.png",
  "21@1x.png",
  "22@1x.png",
  "23.png",
  "24@1x.png",
  "25@1x.png",
  "26@1x.png",
  "27@1x.png",
  "28.png",
  "29.png",
  "30.png",
  "31@1x.png",
  "32@1x.png",
  "33@1x.png",
  "34@1x.png",
  "35@1x.png",
  "36@1x.png",
  "37@1x.png",
  "38@1x.png",
  "39@2x.png",
  "40@1x.png",
  "41@1x.png",
  "42@1x.png",
  "43@1x.png",
  "47@1x.png",
  "48@1x.png",
];

const pinpaiProjects = [
  buildProject("chuweiji-brand-book", "初味季品牌手册", "/public/pinpai/初味季品牌手册", [
    "初味季-VI-源文件-已转曲-02.jpg",
    "初味季-VI-源文件-已转曲-03.jpg",
    "初味季-VI-源文件-已转曲-04.jpg",
    "初味季-VI-源文件-已转曲-05.jpg",
    "初味季-VI-源文件-已转曲-06.jpg",
    "初味季-VI-源文件-已转曲-07.jpg",
    "初味季-VI-源文件-已转曲-08.jpg",
    "初味季-VI-源文件-已转曲-09.jpg",
    "初味季-VI-源文件-已转曲-10.jpg",
    "初味季-VI-源文件-已转曲-11.jpg",
    "初味季-VI-源文件-已转曲-12.jpg",
    "初味季-VI-源文件-已转曲-13.jpg",
    "初味季-VI-源文件-已转曲-14.jpg",
    "初味季-VI-源文件-已转曲-15.jpg",
    "初味季-VI-源文件-已转曲-16.jpg",
    "初味季-VI-源文件-已转曲-17.jpg",
    "初味季-VI-源文件-已转曲-18.jpg",
    "初味季-VI-源文件-已转曲-19.jpg",
    "初味季-VI-源文件-已转曲-20.jpg",
    "初味季-VI-源文件-已转曲-21.jpg",
    "初味季-VI-源文件-已转曲-22.jpg",
    "初味季-VI-源文件-已转曲-23.jpg",
    "初味季-VI-源文件-已转曲-24.jpg",
    "初味季-VI-源文件-已转曲-25.jpg",
    "初味季-VI-源文件-已转曲-26.jpg",
    "初味季-VI-源文件-已转曲-27.jpg",
    "初味季-VI-源文件-已转曲-28.jpg",
    "初味季-VI-源文件-已转曲-29.jpg",
    "初味季-VI-源文件-已转曲-30.jpg",
    "初味季-VI-源文件-已转曲-31.jpg",
    "初味季-VI-源文件-已转曲-32.jpg",
    "初味季-VI-源文件-已转曲-33.jpg",
    "初味季-VI-源文件-已转曲-34.jpg",
    "初味季-VI-源文件-已转曲-35.jpg",
    "初味季-VI-源文件-已转曲-36.jpg",
    "初味季-VI-源文件-已转曲-37.jpg",
    "初味季-VI-源文件-已转曲-38.jpg",
    "初味季-VI-源文件-已转曲-39.jpg",
    "初味季-VI-源文件-已转曲-40.jpg",
    "初味季-VI-源文件-已转曲-42.jpg",
    "初味季-VI-源文件-已转曲_画板 1.jpg"
  ]),
  buildProject("digital-gravity-cn", "数字引力中文画册-c端", "/public/pinpai/数字引力中文画册-c端", [
    "未标题-1-01.jpg",
    "未标题-1-02.jpg",
    "未标题-1-03.jpg",
    "未标题-1-04.jpg",
    "未标题-1-05.jpg",
    "未标题-1-06.jpg",
    "未标题-1-07.jpg",
    "未标题-1-08.jpg",
    "未标题-1-09.jpg",
    "未标题-1-10.jpg",
    "未标题-1-11.jpg",
    "未标题-1-12.jpg",
    "未标题-1-13.jpg",
    "未标题-1-14.jpg",
    "未标题-1-15.jpg",
    "未标题-1-16.jpg",
    "未标题-1-17.jpg",
    "未标题-1-18.jpg",
    "未标题-1-19.jpg",
    "未标题-1-20.jpg",
    "未标题-1-21.jpg",
    "未标题-1-22.jpg",
    "未标题-1-23.jpg",
    "未标题-1-24.jpg",
    "未标题-1-25.jpg",
    "未标题-1-26.jpg",
    "未标题-1-27.jpg",
    "未标题-1-28.jpg",
    "未标题-1-29.jpg",
    "未标题-1-30.jpg",
    "未标题-1-31.jpg",
    "未标题-1-32.jpg"
  ]),
  buildProject("digital-gravity-overseas", "数字引力出海品牌手册", "/public/pinpai/数字引力出海品牌手册", [
    "10 14.56.35.jpg",
    "11 14.56.35.jpg",
    "12 14.56.35.jpg",
    "13 14.56.38.jpg",
    "14 14.56.38.jpg",
    "15 14.56.38.jpg",
    "16 14.56.38.jpg",
    "1封面封底 14.56.34.jpg",
    "2等面封底背面 14.56.34.jpg",
    "3 14.56.34.jpg",
    "4 14.56.34.jpg",
    "5 14.56.34.jpg",
    "6 14.56.34.jpg",
    "7 14.56.35.jpg",
    "8 14.56.35.jpg",
    "9 14.56.35.jpg"
  ]),
  buildProject("digital-gravity-en", "数字引力英文手册-b端", "/public/pinpai/数字引力英文手册-b端", [
    "10.jpg",
    "11.jpg",
    "12.jpg",
    "13.jpg",
    "14.jpg",
    "15.jpg",
    "16.jpg",
    "1封面封底.jpg",
    "2等面封底背面.jpg",
    "3.jpg",
    "4.jpg",
    "5.jpg",
    "6.jpg",
    "7.jpg",
    "8.jpg",
    "9.jpg"
  ]),
  buildProject("adaimao-brand-book", "阿呆猫品牌手册", "/public/pinpai/阿呆猫品牌手册", [
    "阿呆猫视觉识别系统手册-02.jpg",
    "阿呆猫视觉识别系统手册-03.jpg",
    "阿呆猫视觉识别系统手册-04.jpg",
    "阿呆猫视觉识别系统手册-05.jpg",
    "阿呆猫视觉识别系统手册-06.jpg",
    "阿呆猫视觉识别系统手册-07.jpg",
    "阿呆猫视觉识别系统手册-08.jpg",
    "阿呆猫视觉识别系统手册-09.jpg",
    "阿呆猫视觉识别系统手册-10.jpg",
    "阿呆猫视觉识别系统手册-11.jpg",
    "阿呆猫视觉识别系统手册-12.jpg",
    "阿呆猫视觉识别系统手册-13.jpg",
    "阿呆猫视觉识别系统手册-14.jpg",
    "阿呆猫视觉识别系统手册-15.jpg",
    "阿呆猫视觉识别系统手册-16.jpg",
    "阿呆猫视觉识别系统手册-17.jpg",
    "阿呆猫视觉识别系统手册-18.jpg",
    "阿呆猫视觉识别系统手册-19.jpg",
    "阿呆猫视觉识别系统手册-20.jpg",
    "阿呆猫视觉识别系统手册-21.jpg",
    "阿呆猫视觉识别系统手册-22.jpg",
    "阿呆猫视觉识别系统手册-23.jpg",
    "阿呆猫视觉识别系统手册-24.jpg",
    "阿呆猫视觉识别系统手册-25.jpg",
    "阿呆猫视觉识别系统手册-26.jpg",
    "阿呆猫视觉识别系统手册-27.jpg",
    "阿呆猫视觉识别系统手册-28.jpg",
    "阿呆猫视觉识别系统手册-29.jpg",
    "阿呆猫视觉识别系统手册-30.jpg",
    "阿呆猫视觉识别系统手册-31.jpg",
    "阿呆猫视觉识别系统手册-32.jpg",
    "阿呆猫视觉识别系统手册-33.jpg",
    "阿呆猫视觉识别系统手册-34.jpg",
    "阿呆猫视觉识别系统手册-35.jpg",
    "阿呆猫视觉识别系统手册-36.jpg",
    "阿呆猫视觉识别系统手册-37.jpg",
    "阿呆猫视觉识别系统手册_画板 1.jpg"
  ])
];

window.portfolioData = {
  categories: [
    {
      slug: "ui",
      title: "UI设计",
      mode: "gallery",
      cover: "/public/ui/1.jpg",
      notes: ["商城", "工业设备管理", "智慧步道", "陌生人交友"],
      description: "聚合移动端界面、后台系统和交互页面设计。",
      items: toImageItems("/public/ui", uiFiles, "UI 作品")
    },
    {
      slug: "pinpai",
      title: "品牌画册",
      mode: "projects",
      cover: pinpaiProjects[0]?.cover ?? "",
      notes: ["品牌手册", "招商画册"],
      description: "用于展示品牌概念、画册排版与整体品牌视觉延展。",
      projects: pinpaiProjects
    },
    {
      slug: "meichen",
      title: "美陈设计",
      mode: "gallery",
      cover: "",
      notes: ["活动效果", "空间陈列"],
      description: "展示活动空间、橱窗、美陈装置与整体氛围效果。",
      items: []
    }
  ]
};
